version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/test-deploy
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 180
  AfterInstall:
    - location: codedeploy/after_install.sh
      runas: centos
      timeout: 180