version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/test-deploy
    overwrite: true
permissions:
  - object: /var/www/test-deploy/codedeploy
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 180
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 180