version: 0.2

run-as: root

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum update -y
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - cd /var/www/test-deploy | composer install
artifacts:
  files:
    - '**/*'